# This container installs spruce
FROM gcc:9.2 AS build

ENV HOME=/home/dockeruser
RUN mkdir /home/dockeruser && \
    touch /home/dockeruser/.bashrc && \
    chmod -R 777 /home/dockeruser 

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

# Install Cmake and Boost
RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
        wget \
        cmake \
        libgtest-dev \
        libboost-all-dev && \
    apt-get clean

# Install LEMON
RUN wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz && \
    tar xvf lemon-1.3.1.tar.gz && \
	cd lemon-1.3.1 && \
    mkdir build && cd build && \
    cmake .. && make && make install

#####
##Above this line could be a base image
######

# Install SPRUCE (commit e5ffc8)

RUN git clone https://github.com/raphael-group/spruce.git && \
    cd spruce && \
    git checkout e5ffc8 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make

FROM ubuntu:20.04

# Install gzip
RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
        gzip && \
    apt-get clean

COPY --from=build /usr/local/include /usr/local/include
RUN mkdir spruce
COPY --from=build spruce/build spruce
COPY ./code /code

RUN ls /
RUN ls ./
RUN ls spruce
