FROM python:3.7

ENV HOME=/home/dockeruser
RUN mkdir /home/dockeruser && \
    touch /home/dockeruser/.bashrc && \
    chmod -R 777 /home/dockeruser 

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
        iproute2 \
        sudo \
        lxc \
        libltdl7 \
        ssh \
        vim \
        gnupg2 \
        curl \
        wget \
        bzip2 \
        ca-certificates \
        python3 \
        python3-dev \
        python3-pip

# copy the phyloflow/spruce_to_physigs/code directory into the container. 
# NOTE this says the local code is in '.' b/c the build_spruce_to_physigs_container.sh script 
# uses  '..' as the context for the build process. Necessary to avoid this issue:
# https://stackoverflow.com/questions/27068596/how-to-include-files-outside-of-dockers-build-context
COPY ./code /code

RUN ls -al /
RUN ls -al /code/
