# This container installs pyclone, pyclone-vi, and the local python 
# code from phyloflow/pyclone/code/
# Conda is used to manage the python env(s) inside the container:
# Use 'conda run ..' with either 'pyclone' or 'pyclone-vi' to use
# those packages.


FROM ubuntu:20.04

ENV HOME=/home/dockeruser
RUN mkdir /home/dockeruser && \
    touch /home/dockeruser/.bashrc && \
    chmod -R 777 /home/dockeruser 

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
        iproute2 \
        sudo \
        lxc \
        libltdl7 \
        ssh \
        vim \
        gnupg2 \
        curl \
        wget \
        bzip2 \
        ca-certificates

#put a fake screen in the container so pyclone can import tkinter for a graph it makes
# https://stackoverflow.com/questions/46613117/why-does-conda-install-tk-not-work-in-my-docker-container-even-though-it-says-it
RUN apt-get -qq install --no-install-recommends \
		xvfb 

#pyclone-vi doesn't have a real conda package so the source must be installed over pip using git
RUN apt-get -qq install --no-install-recommends \
		git	


#####
##Above this line could be a base image
## *Or maybe not, pyclone is python2.7 only so not sure we should 
## have a common base image that supports that
######

#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh  -O ~/miniconda.sh
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-py27_4.8.3-Linux-x86_64.sh  -O ~/miniconda.sh

RUN /bin/bash ~/miniconda.sh -b -p /opt/conda
RUN rm ~/miniconda.sh
RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/dockeruser/.bashrc
RUN echo "conda activate base" >> /home/dockeruser/.bashrc

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

#######
## Begin pyclone-vi specific install
######

RUN wget https://raw.githubusercontent.com/Roth-Lab/pyclone-vi/master/requirements.txt
RUN conda create -n pyclone-vi --file requirements.txt --yes
RUN conda run -v -n pyclone-vi pip install -v git+https://github.com/aroth85/pyclone-vi.git


#######
## End pyclone-vi specific install
#####

#try to reduce the size of the image
RUN conda clean --all --yes

#system wide conda status
RUN conda info

#this command prefix will run what comes in the suffix
#in a bash shell with all the paths and dependencies installed
#in the 'base' conda env. Single quotes will be
#needed around the command suffix
ENV RUN_IN_CONDA="bash -i -c "


#this will print all installed packages and their versions
RUN $RUN_IN_CONDA 'conda list'

# copy the phyloflow/pyclone/code directory into the container. 
# NOTE this says the local code is in '.' b/c the build_pyclone_container.sh script 
# uses  '..' as the context for the build process. Necessary to avoid this issue:
# https://stackoverflow.com/questions/27068596/how-to-include-files-outside-of-dockers-build-context
COPY ./code /code

RUN ls -al /
RUN ls -al /code/
